version: "3.9"

services:
  static-images:
    container_name: nginx
    image: static-images
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"

  pdf-generation:
    container_name: pdf-generation
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/src/app/results
    environment:
      IMAGE_SERVICE_BASE_URL: http://static-images:8080
      INSTANCE_SIZE: ${INSTANCE_SIZE:-small}
      INSTANCES_CONCURRENCY: ${INSTANCES_CONCURRENCY:-1}
      MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS:-150}
      ENGINE: ${ENGINE:-chrome}
      ITERATIONS: 20
    depends_on:
      - static-images
